package com.muswall.app.service

import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.media.MediaMetadata
import android.media.session.MediaController
import android.media.session.MediaSessionManager
import android.media.session.PlaybackState
import android.net.Uri
import android.os.Build
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import com.muswall.app.data.PreferencesManager
import com.muswall.app.python.PythonBridge
import com.muswall.app.wallpaper.MusicWallpaperService
import com.muswall.app.wallpaper.WallpaperHelper
import kotlinx.coroutines.*
import java.net.HttpURLConnection
import java.net.URL
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicLong

class MediaNotificationListenerService : NotificationListenerService() {
    companion object { const val ACTION_TRACK_CHANGED="com.muswall.app.ACTION_TRACK_CHANGED";const val ACTION_PLAYBACK_STATE_CHANGED="com.muswall.app.ACTION_PLAYBACK_STATE_CHANGED";const val ACTION_WALLPAPER_APPLIED="com.muswall.app.ACTION_WALLPAPER_APPLIED";const val EXTRA_TRACK_TITLE="extra_track_title";const val EXTRA_ARTIST="extra_artist";const val EXTRA_IS_PLAYING="extra_is_playing";const val EXTRA_STATUS_MESSAGE="extra_status_message";private const val TAG="MusWallMedia" }
    private val scope=CoroutineScope(SupervisorJob()+Dispatchers.Main.immediate);private val generation=AtomicLong(0);private lateinit var prefs:PreferencesManager;private lateinit var wallpaperHelper:WallpaperHelper;private var sessionManager:MediaSessionManager?=null;private var activeController:MediaController?=null;private var currentTrackId="";private var playing=false;private var generationJob:Job?=null;private val notificationArtwork=ConcurrentHashMap<String,Bitmap>()
    private val callback=object:MediaController.Callback(){override fun onPlaybackStateChanged(s:PlaybackState?)=handlePlayback(s);override fun onMetadataChanged(m:MediaMetadata?)=handleMetadata(m,true);override fun onSessionDestroyed(){handlePlayback(null);refreshActiveSessions()}};private val sessionsListener=MediaSessionManager.OnActiveSessionsChangedListener{selectBestController(it)}
    override fun onCreate(){super.onCreate();prefs=PreferencesManager.getInstance(this);wallpaperHelper=WallpaperHelper(this);PythonBridge.initialize(this)}
    override fun onListenerConnected(){super.onListenerConnected();try{activeNotifications?.forEach{cacheNotificationArtwork(it)}}catch(t:Throwable){android.util.Log.w(TAG,"notification scan failed",t)};connectSessions()}
    private fun connectSessions(){try{sessionManager=getSystemService(Context.MEDIA_SESSION_SERVICE) as MediaSessionManager;val c=ComponentName(this,MediaNotificationListenerService::class.java);sessionManager?.addOnActiveSessionsChangedListener(sessionsListener,c);refreshActiveSessions()}catch(t:Throwable){android.util.Log.w(TAG,"session connection failed",t);broadcastWallpaperApplied("Music detection is not connected. Enable Notification access.")}}
    private fun refreshActiveSessions(){try{selectBestController(sessionManager?.getActiveSessions(ComponentName(this,MediaNotificationListenerService::class.java)))}catch(t:Throwable){android.util.Log.w(TAG,"session refresh failed",t)}}
    private fun selectBestController(list:List<MediaController>?){val l=list.orEmpty();switchController(l.firstOrNull{it.playbackState?.state==PlaybackState.STATE_PLAYING}?:l.firstOrNull{it.metadata!=null}?:l.firstOrNull())}
    private fun switchController(c:MediaController?){if(c?.sessionToken==activeController?.sessionToken){c?.playbackState?.let{handlePlayback(it)};c?.metadata?.let{handleMetadata(it,false)};return};runCatching{activeController?.unregisterCallback(callback)};activeController=c;currentTrackId="";if(c==null){handlePlayback(null);broadcastTrack("No music detected","Waiting for a music player");return};runCatching{c.registerCallback(callback)};handlePlayback(c.playbackState);c.metadata?.let{handleMetadata(it,true)}}
    private fun handlePlayback(s:PlaybackState?){val now=s?.state==PlaybackState.STATE_PLAYING;val was=playing;playing=now;broadcastPlaybackState(now);if(!now){generation.incrementAndGet();generationJob?.cancel();currentTrackId="";prefs.liveMusicPlaying=false;if(prefs.liveWallpaperEnabled)refreshLive();if(was&&prefs.restoreOnPause)broadcastWallpaperApplied("Music stopped • original wallpaper restored")}else if(!was)activeController?.metadata?.let{handleMetadata(it,true)}}
    private fun handleMetadata(m:MediaMetadata?,force:Boolean){if(m==null)return;val title=m.getString(MediaMetadata.METADATA_KEY_TITLE)?.trim().orEmpty().ifEmpty{"Unknown title"};val artist=m.getString(MediaMetadata.METADATA_KEY_ARTIST)?.trim().orEmpty().ifEmpty{"Unknown artist"};broadcastTrack(title,artist);prefs.lastTrackTitle=title;prefs.lastArtist=artist;val artUri=firstNonBlank(m.getString(MediaMetadata.METADATA_KEY_ALBUM_ART_URI),m.getString(MediaMetadata.METADATA_KEY_ART_URI),if(Build.VERSION.SDK_INT>=21)m.getString(MediaMetadata.METADATA_KEY_DISPLAY_ICON_URI)else null);val id="${activeController?.packageName.orEmpty()}\u0000${m.getString(MediaMetadata.METADATA_KEY_MEDIA_ID).orEmpty()}\u0000$title\u0000$artist\u0000$artUri";if(!force&&id==currentTrackId)return;currentTrackId=id;if(!prefs.isAutoEnabled||!playing||prefs.wallpaperMode!=PreferencesManager.MODE_MUSIC)return;if(!prefs.liveWallpaperEnabled){broadcastWallpaperApplied("Music detected • enable MusWall Live Wallpaper once");return};val token=generation.incrementAndGet();generationJob?.cancel();generationJob=scope.launch(Dispatchers.Default){val art=extractArtwork(m,activeController?.packageName.orEmpty());if(art==null){broadcastWallpaperApplied("Track detected, but no album artwork was available");return@launch};try{renderAndSendToLiveWallpaper(art,token)}finally{if(!art.isRecycled)art.recycle()}}}
    private suspend fun renderAndSendToLiveWallpaper(art:Bitmap,token:Long){if(token!=generation.get()||!playing||!prefs.liveWallpaperEnabled)return;val dm=resources.displayMetrics;val result=PythonBridge.generateWallpaper(art,(dm.widthPixels*.58f).toInt().coerceIn(480,720),(dm.heightPixels*.58f).toInt().coerceIn(900,1440),prefs.blurRadius.toFloat(),prefs.darkness/100f,prefs.artScale/100f,42,true,prefs.effect,prefs.blurType,prefs.coverHeight,prefs.coverOffset,prefs.transitionHeight,prefs.showLyrics,buildLyrics(),prefs.photoSource,prefs.customPhotoUri)?:return;try{if(token!=generation.get()||!playing||!prefs.liveWallpaperEnabled)return;wallpaperHelper.saveLastArtwork(art);wallpaperHelper.saveCurrentForLiveWallpaper(result);prefs.liveMusicPlaying=true;refreshLive();broadcastWallpaperApplied("Live wallpaper updated instantly")}finally{if(!result.isRecycled)result.recycle()}}
    private fun buildLyrics():String=activeController?.metadata?.getString("android.media.metadata.LYRICS").orEmpty()
    private suspend fun extractArtwork(m:MediaMetadata,packageName:String):Bitmap?{try{when(prefs.photoSource){PreferencesManager.PHOTO_CUSTOM->if(prefs.customPhotoUri.isNotBlank())loadArtworkUri(prefs.customPhotoUri)?.let{return it};PreferencesManager.PHOTO_ART->m.getBitmap(MediaMetadata.METADATA_KEY_ART)?.let{downsampleArtwork(it)?.let{return it}};PreferencesManager.PHOTO_DISPLAY_ICON->m.getBitmap(MediaMetadata.METADATA_KEY_DISPLAY_ICON)?.let{downsampleArtwork(it)?.let{return it}};PreferencesManager.PHOTO_NOTIFICATION->notificationArtwork[packageName]?.let{downsampleArtwork(it)?.let{return it}};else->m.getBitmap(MediaMetadata.METADATA_KEY_ALBUM_ART)?.let{downsampleArtwork(it)?.let{return it}}}}
        val uris=listOfNotNull(m.getString(MediaMetadata.METADATA_KEY_ALBUM_ART_URI),m.getString(MediaMetadata.METADATA_KEY_ART_URI),if(Build.VERSION.SDK_INT>=21)m.getString(MediaMetadata.METADATA_KEY_DISPLAY_ICON_URI)else null).filter{it.isNotBlank()}.distinct();for(u in uris){loadArtworkUri(u)?.let{return it}};if(prefs.photoFallback)notificationArtwork[packageName]?.let{downsampleArtwork(it)?.let{return it}}}catch(t:Throwable){android.util.Log.w(TAG,"art extraction failed",t)};return null}
    private suspend fun loadArtworkUri(text:String):Bitmap?=withContext(Dispatchers.IO){try{val uri=Uri.parse(text);val decoded=when(uri.scheme?.lowercase()){"http","https"->{var c:HttpURLConnection?=null;try{c=URL(text).openConnection() as HttpURLConnection;c.connectTimeout=2500;c.readTimeout=4000;c.setRequestProperty("User-Agent","MusWall/1.9");c.connect();if(c.responseCode !in 200..299)return@withContext null;c.inputStream.use{BitmapFactory.decodeStream(it)}}finally{c?.disconnect()}}else->contentResolver.openInputStream(uri)?.use{BitmapFactory.decodeStream(it)}};decoded?.let{downsampleArtwork(it)}}catch(_:Throwable){null}}
    private fun cacheNotificationArtwork(sbn:StatusBarNotification){try{val icon=if(Build.VERSION.SDK_INT>=23)sbn.notification.getLargeIcon()else null;if(icon==null)return;val d=icon.loadDrawable(this)?:return;val w=d.intrinsicWidth.coerceAtLeast(1).coerceAtMost(900);val h=d.intrinsicHeight.coerceAtLeast(1).coerceAtMost(900);val b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas(b).also{c->d.setBounds(0,0,w,h);d.draw(c)};notificationArtwork.put(sbn.packageName,b)?.let{if(!it.isRecycled)it.recycle()}}catch(t:Throwable){android.util.Log.w(TAG,"notification art failed",t)}}
    private fun downsampleArtwork(b:Bitmap):Bitmap?=try{val s=b.copy(Bitmap.Config.ARGB_8888,false)?:return null;if(s.width<=900&&s.height<=900)return s;val scale=minOf(900f/s.width,900f/s.height);Bitmap.createScaledBitmap(s,(s.width*scale).toInt().coerceAtLeast(1),(s.height*scale).toInt().coerceAtLeast(1),true).also{if(it!==s&&!s.isRecycled)s.recycle()}}catch(_:Throwable){null};private fun firstNonBlank(vararg v:String?):String?=v.firstOrNull{!it.isNullOrBlank()}
    private fun refreshLive()=sendBroadcast(Intent(MusicWallpaperService.ACTION_REFRESH).setPackage(packageName));private fun broadcastTrack(t:String,a:String)=sendBroadcast(Intent(ACTION_TRACK_CHANGED).setPackage(packageName).putExtra(EXTRA_TRACK_TITLE,t).putExtra(EXTRA_ARTIST,a));private fun broadcastPlaybackState(p:Boolean)=sendBroadcast(Intent(ACTION_PLAYBACK_STATE_CHANGED).setPackage(packageName).putExtra(EXTRA_IS_PLAYING,p));private fun broadcastWallpaperApplied(s:String)=sendBroadcast(Intent(ACTION_WALLPAPER_APPLIED).setPackage(packageName).putExtra(EXTRA_STATUS_MESSAGE,s));override fun onNotificationPosted(sbn:StatusBarNotification?){sbn?.let{cacheNotificationArtwork(it)};refreshActiveSessions()};override fun onNotificationRemoved(sbn:StatusBarNotification?){refreshActiveSessions()};override fun onDestroy(){generation.incrementAndGet();generationJob?.cancel();runCatching{sessionManager?.removeOnActiveSessionsChangedListener(sessionsListener)};runCatching{activeController?.unregisterCallback(callback)};notificationArtwork.values.forEach{if(!it.isRecycled)it.recycle()};notificationArtwork.clear();scope.cancel();super.onDestroy()}
}
